
#The cloud/production profile
#The environment variable $DATABASE_URL to be used in the cloud deployment env
spring.datasource.url= ${DATABASE_URL}

#JWT-JSON WEB TOKENS

#Key depends on JWT algorithm; If RSA => needs public,private; if HMAC => needs only single key
app.jwt.secret= ${APP_JWT_SECRET}
#JWT EXPIRATION
app.jwt.expiration-in.ms= ${APP_JWT_EXPIRATION_IN_MS}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
